//@target illustrator
/*
 * CRYPTO.COM ARENA - FIGUEROA ENTRANCE: WINDOW GRAPHICS TEMPLATE (Adobe Illustrator)
 *
 * Builds a layered, editable Illustrator template at 1:10 scale from the field
 * measurements in the spreadsheet named in SOURCE below.
 *
 * HOW TO RUN
 *   1. Illustrator > File > Scripts > Other Script... (Ctrl/Cmd+F12) and choose this file.
 *   2. Wait a minute or two while it draws the panels and their artboards.
 *   3. File > Save As > Adobe Illustrator (.ai).
 *
 * WHAT YOU GET
 *   Artboard 1        "Elevation" - the whole window wall. Design here.
 *   Artboards 2-526   One per glass panel (A01 ... O35), for output with bleed.
 *   Layer ARTWORK     Your design (bottom layer, unlocked, printing).
 *   Layers MULLIONS, TRIM, SAFE AREA, LABELS, INFO
 *                     Template guides - locked and non-printing.
 *
 * To change the scale, bleed, row alignment, etc. edit SETTINGS below and run again.
 * DATA is generated from the spreadsheet by tools/build.mjs; a size or a mullion can
 * also be corrected directly in DATA before running.
 * One artboard per panel needs Illustrator CC 2018 (v22) or later.
 */
(function (global) {

    // ------------------------------------------------------------------
    // SETTINGS
    // ------------------------------------------------------------------
    var SETTINGS = {
        scale: 10,                // document scale 1:10 - everything is drawn at 10% of actual size
        verticalMullion: 0.5,     // inches (actual) between panels in a row
        horizontalMullion: 2.25,  // inches (actual) - height of each MULLION in DATA
        bleed: 0.5,               // inches (actual) per side - set as the document bleed
        safeMargin: 1,            // inches (actual) - keep text and logos this far inside each panel
        rowAlignment: 'mullions', // 'mullions' = line up the vertical mullions (best fit), or 'left', 'center', 'right'
        firstRowIsTop: true,      // true = the first spreadsheet row (row A) is the top of the wall
        panelArtboards: true      // one artboard per panel, for output
    };

    // ------------------------------------------------------------------
    // DATA - actual inches, top to bottom as in the spreadsheet:
    //   [height, [widths of columns 1, 2, 3 ... left to right]]  a row of glass
    //   MULLION                                                  a horizontal mullion
    // Rows with no MULLION between them butt together with no gap.
    // NOTES lists panels to verify; they are marked on the template.
    // ------------------------------------------------------------------
    var MULLION = 'mullion';
    // @@DATA-BEGIN (generated by tools/build.mjs)
    var PROJECT = 'Crypto.com Arena - Figueroa Entrance';
    var REVISION = 'v2';
    var SOURCE = 'Crypto.com Arena Figueroa Entrance - Windows (3).csv';
    var WALL = [
        [74.5, [39.75, 62.25, 62.25, 63, 62.25, 62.25, 62.25, 67.25, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 66.875, 67, 67, 67, 67, 57, 57, 57.5, 57.5, 57.5, 58.25, 16]], // A
        MULLION,
        [40.5, [41, 62, 62, 62, 62, 62, 62, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 66.875, 67, 67, 67, 57, 57, 57, 57.5, 57.5, 57.5, 58.25, 23.5]], // B
        MULLION,
        [74, [43.25, 62, 62, 62, 62, 62, 62, 67, 66.5, 66.5, 66.5, 66.5, 66.5, 66.5, 66.5, 66.5, 66, 66, 66, 66, 66, 66, 66, 66, 67, 67, 67, 67, 57, 57, 57.5, 57.5, 57.5, 58.24, 23.5]], // C
        MULLION,
        [70.5, [45.24, 62, 61.5, 61.5, 61.5, 61.5, 61.5, 66.5, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 57, 57, 57.5, 57.5, 57.5, 57, 28]], // D
        [36.5, [46.5, 62, 61, 61, 61, 61, 61, 65.75, 66, 66, 66, 66, 66, 66, 66, 66.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 66, 66, 66, 57, 57, 57, 57.5, 57.5, 57.5, 57, 31]], // E
        MULLION,
        [7.25, [46.5, 61, 61, 61, 61, 61, 61, 66, 66, 66, 66, 66, 66, 66, 66, 66, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 66, 66, 66, 66, 57, 57, 57.5, 57.5, 57.5, 57, 31]], // F
        [70.5, [48.5, 61, 61, 61, 61, 61, 61, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65.5, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 57, 57, 56.75, 56.75, 56.75, 57, 36]], // G
        [36.5, [49.75, 60.375, 60.125, 60.125, 60.125, 60.125, 60.125, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 57, 57, 56.5, 56.5, 56.5, 56.5, 39]], // H
        MULLION,
        [7.25, [49.75, 60.125, 60.25, 60.25, 60.25, 60.25, 60.25, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 56, 56, 56.5, 56.5, 56.5, 56.5, 39]], // I
        [70.5, [52.25, 59.755, 60.25, 60.25, 60.25, 60.25, 60.25, 65, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 56, 56, 56.5, 56.5, 56.5, 56, 44]], // J
        [36.5, [53.75, 59.75, 59.75, 59.75, 59.75, 59.75, 59.75, 64.5, 64.5, 64, 64, 64, 64, 64, 64, 64, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 56, 56, 56, 56, 56, 56, 47]], // K
        MULLION,
        [7.25, [53.375, 59.5, 59.5, 59.5, 59.5, 59.5, 59.5, 64.5, 64, 64, 64, 64, 64, 64, 64, 64, 64.25, 64.25, 64.25, 64.25, 64.25, 64.25, 64.5, 64.5, 64.5, 64.5, 64.5, 64.5, 56, 56, 56, 56, 56, 56, 47]], // L
        [70.5, [55.375, 59.5, 59.5, 59.5, 59.5, 59.5, 59.5, 64.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.75, 63.75, 63.75, 63.75, 55.25, 55.25, 55.25, 55.25, 55.25, 55.5, 55.625]], // M
        [36.5, [56.625, 59, 59, 59, 59, 59, 59, 63.625, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.75, 63.75, 63.75, 63.75, 55.25, 55.25, 55.25, 55.25, 55.25, 56.625, 56.625]], // N
        MULLION,
        [7.25, [56.75, 59, 58.75, 58.75, 58.75, 58.75, 58.75, 63.25, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 63.5, 55.5, 55.25, 55.25, 55.25, 55.25, 55, 55]], // O
        MULLION
    ];
    var NOTES = {
        G31: 'blank in the spreadsheet - drawn at 56.75" x 70.5" from the previous version of the sheet'
    };
    // @@DATA-END
    var ROWS = panelRows(WALL);

    var LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    var CANVAS = 16383;        // Illustrator's canvas, in points (227.54 in)
    var MAX_ARTBOARDS = 1000;
    var CAP = 0.716;           // cap height of Arial as a fraction of the font size (for centering text)
    var FONTS = {
        regular: ['ArialMT', 'MyriadPro-Regular'],
        bold: ['Arial-BoldMT', 'MyriadPro-Bold']
    };

    // ------------------------------------------------------------------
    // Formatting helpers
    // ------------------------------------------------------------------
    function num(n) {
        return String(Math.round(n * 1000) / 1000);
    }

    function pad2(n) {
        return n < 10 ? '0' + n : String(n);
    }

    function feetInches(inches) {
        var eighths = Math.round(inches * 8);
        var feet = Math.floor(eighths / 96);
        var rest = eighths - feet * 96;
        var whole = Math.floor(rest / 8);
        var frac = rest - whole * 8;
        var den = 8;
        var s = feet + "' " + whole;
        if (frac) {
            while (frac % 2 === 0) {
                frac /= 2;
                den /= 2;
            }
            s += '-' + frac + '/' + den;
        }
        return s + '"';
    }

    function thousands(n) {
        var s = String(Math.round(n));
        var out = '';
        while (s.length > 3) {
            out = ',' + s.slice(-3) + out;
            s = s.slice(0, -3);
        }
        return s + out;
    }

    function clamp(v, lo, hi) {
        return Math.max(lo, Math.min(hi, v));
    }

    // ------------------------------------------------------------------
    // Layout - pure geometry in actual inches, origin at the top-left of the
    // wall, y growing downwards. No Illustrator calls in here.
    // ------------------------------------------------------------------
    function panelRows(wall) {
        var rows = [];
        for (var i = 0; i < wall.length; i++) {
            if (wall[i] !== MULLION) {
                rows.push(wall[i]);
            }
        }
        return rows;
    }

    // Runs of rows with no horizontal mullion between them, e.g. ['D-E', 'F-G-H']
    function buttedRows(wall) {
        var runs = [];
        var run = [];
        var r = 0;
        for (var i = 0; i <= wall.length; i++) {
            if (i === wall.length || wall[i] === MULLION) {
                if (run.length > 1) {
                    runs.push(run.join('-'));
                }
                run = [];
            } else {
                run.push(LETTERS.charAt(r));
                r++;
            }
        }
        return runs;
    }

    function computeLayout(wall, s) {
        var V = s.verticalMullion;
        var rows = panelRows(wall);
        var n = rows.length;
        var r, c, i, k;
        if (n < 1 || n > LETTERS.length) {
            throw new Error('Expected 1 to ' + LETTERS.length + ' rows of panels, found ' + n + '.');
        }

        // Width of each row, and the average position of its vertical mullions,
        // with every row starting at x = 0.
        var widths = [];
        var means = [];
        for (r = 0; r < n; r++) {
            var ws = rows[r][1];
            var x = 0;
            var sum = 0;
            for (c = 0; c < ws.length; c++) {
                x += ws[c];
                if (c < ws.length - 1) {
                    sum += x + V / 2;
                    x += V;
                }
            }
            widths.push(x);
            means.push(ws.length > 1 ? sum / (ws.length - 1) : x / 2);
        }

        // Sideways offset of each row. The rows are not all the same width, so
        // 'mullions' shifts each row until the average of its vertical-mullion
        // positions matches the other rows (the least-squares best fit).
        var mode = String(s.rowAlignment).toLowerCase();
        if (mode !== 'left' && mode !== 'center' && mode !== 'right') {
            mode = 'mullions';
        }
        for (r = 1; r < n; r++) {
            if (mode === 'mullions' && rows[r][1].length !== rows[0][1].length) {
                mode = 'center'; // mullions can only be matched when every row has the same panel count
            }
        }
        var maxWidth = Math.max.apply(null, widths);
        var maxMean = Math.max.apply(null, means);
        var offsets = [];
        var minOffset = Infinity;
        for (r = 0; r < n; r++) {
            var o;
            if (mode === 'left') {
                o = 0;
            } else if (mode === 'right') {
                o = maxWidth - widths[r];
            } else if (mode === 'center') {
                o = (maxWidth - widths[r]) / 2;
            } else {
                o = maxMean - means[r];
            }
            o = Math.round(o * 16) / 16;
            offsets.push(o);
            if (o < minOffset) {
                minOffset = o;
            }
        }

        // Stack the bands top to bottom in spreadsheet order: rows of glass, with
        // a horizontal mullion wherever the spreadsheet has one
        var bands = [];
        r = 0;
        for (i = 0; i < wall.length; i++) {
            if (wall[i] === MULLION) {
                bands.push({ row: -1, h: s.horizontalMullion });
            } else {
                bands.push({ row: r, h: rows[r][0] });
                r++;
            }
        }
        if (!s.firstRowIsTop) {
            bands.reverse();
        }
        var y = 0;
        var rowY = [];
        for (i = 0; i < bands.length; i++) {
            bands[i].y = y;
            if (bands[i].row >= 0) {
                rowY[bands[i].row] = y;
            }
            y += bands[i].h;
        }

        // Panels and the vertical mullions between them
        var rowBoxes = [];
        var panels = [];
        var vertical = [];
        var area = 0;
        for (r = 0; r < n; r++) {
            var h = rows[r][0];
            var ws2 = rows[r][1];
            var px = offsets[r] - minOffset;
            rowBoxes.push({ row: r, letter: LETTERS.charAt(r), x: px, y: rowY[r], w: widths[r], h: h });
            for (c = 0; c < ws2.length; c++) {
                panels.push({ id: LETTERS.charAt(r) + pad2(c + 1), row: r, col: c + 1, x: px, y: rowY[r], w: ws2[c], h: h });
                area += ws2[c] * h;
                px += ws2[c];
                if (c < ws2.length - 1) {
                    vertical.push({ row: r, col: c + 1, x: px, y: rowY[r], w: V, h: h });
                    px += V;
                }
            }
        }

        var width = 0;
        for (r = 0; r < n; r++) {
            width = Math.max(width, rowBoxes[r].x + rowBoxes[r].w);
        }

        // Horizontal mullions span the rows directly above and below them
        var horizontal = [];
        for (i = 0; i < bands.length; i++) {
            if (bands[i].row >= 0) {
                continue;
            }
            var left = Infinity;
            var right = -Infinity;
            for (k = i - 1; k <= i + 1; k += 2) {
                if (k >= 0 && k < bands.length && bands[k].row >= 0) {
                    var b = rowBoxes[bands[k].row];
                    left = Math.min(left, b.x);
                    right = Math.max(right, b.x + b.w);
                }
            }
            if (left === Infinity) {
                left = 0;           // no row next to it: run across the whole wall
                right = width;
            }
            horizontal.push({ x: left, y: bands[i].y, w: right - left, h: bands[i].h });
        }

        var rowOrder = [];
        for (i = 0; i < bands.length; i++) {
            if (bands[i].row >= 0) {
                rowOrder.push(bands[i].row);
            }
        }
        return {
            rows: rowBoxes,
            panels: panels,
            vertical: vertical,
            horizontal: horizontal,
            width: width,
            height: y,
            area: area / 144,
            alignment: mode,
            topRow: rowOrder[0],
            bottomRow: rowOrder[rowOrder.length - 1],
            minRowWidth: Math.min.apply(null, widths),
            maxRowWidth: maxWidth
        };
    }

    // Panels whose width jumps away from BOTH the panel above and the panel
    // below in the same column (likely typos in the spreadsheet).
    function findOutliers(rows, tolerance) {
        var out = [];
        var r, c;
        for (r = 1; r < rows.length - 1; r++) {
            var ws = rows[r][1];
            for (c = 0; c < ws.length; c++) {
                if (c >= rows[r - 1][1].length || c >= rows[r + 1][1].length) {
                    continue;
                }
                var above = rows[r - 1][1][c];
                var below = rows[r + 1][1][c];
                var up = ws[c] - above;
                var down = ws[c] - below;
                if (up * down > 0 && Math.abs(up) > tolerance && Math.abs(down) > tolerance) {
                    out.push({ id: LETTERS.charAt(r) + pad2(c + 1), col: c + 1, w: ws[c], above: above, below: below });
                }
            }
        }
        return out;
    }

    // Panels to verify before production: widths that jump away from the
    // panels above and below, plus anything listed in NOTES.
    function findChecks(rows, notes) {
        var out = [];
        var outliers = findOutliers(rows, 3);
        var i, id;
        for (i = 0; i < outliers.length; i++) {
            var o = outliers[i];
            out.push({ id: o.id, text: num(o.w) + '" wide, but column ' + o.col + ' is ' + num(o.above) +
                '" above and ' + num(o.below) + '" below (typo?)' });
        }
        for (id in notes) {
            if (notes.hasOwnProperty(id)) {
                out.push({ id: id, text: notes[id] });
            }
        }
        return out;
    }

    // ------------------------------------------------------------------
    // Illustrator helpers
    // ------------------------------------------------------------------
    function findFont(names) {
        for (var i = 0; i < names.length; i++) {
            try {
                return app.textFonts.getByName(names[i]);
            } catch (e) {
                // try the next one
            }
        }
        return null;
    }

    // A global process swatch, so a color can be changed everywhere at once
    // from the Swatches panel. Falls back to a plain CMYK color.
    function swatch(doc, name, c, m, y, k) {
        var cmyk = new CMYKColor();
        cmyk.cyan = c;
        cmyk.magenta = m;
        cmyk.yellow = y;
        cmyk.black = k;
        try {
            var spot = doc.spots.add();
            spot.name = name;
            spot.color = cmyk;
            spot.colorType = ColorModel.PROCESS;
            var color = new SpotColor();
            color.spot = spot;
            color.tint = 100;
            return color;
        } catch (e) {
            return cmyk;
        }
    }

    function addLayer(doc, name) {
        var layer = doc.layers.add();
        layer.name = name;
        return layer;
    }

    function group(parent, name) {
        var g = parent.groupItems.add();
        g.name = name;
        return g;
    }

    // Rectangle in points. style: { fill, stroke, width, dashes }
    function box(parent, left, top, w, h, style, name) {
        var r = parent.pathItems.rectangle(top, left, w, h);
        if (style.fill) {
            r.filled = true;
            r.fillColor = style.fill;
        } else {
            r.filled = false;
        }
        if (style.stroke) {
            r.stroked = true;
            r.strokeColor = style.stroke;
            r.strokeWidth = style.width;
            if (style.dashes) {
                r.strokeDashes = style.dashes;
            }
        } else {
            r.stroked = false;
        }
        if (name) {
            r.name = name;
        }
        return r;
    }

    // Point text; (x, y) is the baseline of the first line, in points.
    // lines, sizes and fonts are parallel arrays - one entry per line.
    function text(parent, x, y, lines, sizes, fonts, color, justification, name) {
        var t = parent.textFrames.pointText([x, y]);
        t.contents = lines.join('\r');
        t.textRange.characterAttributes.fillColor = color;
        t.textRange.paragraphAttributes.justification = justification;
        for (var i = 0; i < lines.length; i++) {
            var attrs = t.paragraphs[i].characterAttributes;
            attrs.size = sizes[i];
            if (fonts[i]) {
                attrs.textFont = fonts[i];
            }
        }
        if (name) {
            t.name = name;
        }
        return t;
    }

    function printPreset() {
        var list = app.startupPresetsList;
        for (var i = 0; i < list.length; i++) {
            if (/print/i.test(list[i])) {
                return list[i];
            }
        }
        return list.length ? list[0] : 'Print';
    }

    function newDocument(w, h, bleed, notes) {
        var preset = new DocumentPreset();
        preset.title = PROJECT + ' - Window Graphics ' + REVISION + ' 1-' + SETTINGS.scale;
        preset.width = w;
        preset.height = h;
        preset.units = RulerUnits.Inches;
        preset.colorMode = DocumentColorSpace.CMYK;
        preset.rasterResolution = DocumentRasterResolution.HighResolution;
        preset.numArtboards = 1;
        var bleedSet = true;
        try {
            preset.documentBleedLink = true;
            preset.documentBleedOffsetRect = [bleed, bleed, bleed, bleed];
        } catch (e) {
            bleedSet = false;
        }
        var doc;
        try {
            doc = app.documents.addDocument(printPreset(), preset);
        } catch (e2) {
            doc = app.documents.add(DocumentColorSpace.CMYK, w, h);
            bleedSet = false;
        }
        if (!bleedSet) {
            notes.push('Set the bleed by hand: File > Document Setup > Bleed ' + num(bleed / 72) + ' in (all sides).');
        }
        return doc;
    }

    // ------------------------------------------------------------------
    // Drawing
    // ------------------------------------------------------------------
    function draw(doc, L, K, checks, notes) {
        var s = SETTINGS;
        var i, r, p;
        var ab = doc.artboards[0].artboardRect;
        var ox = ab[0];
        var oy = ab[1];
        var X = function (x) { return ox + x * K; };   // actual inches -> document points
        var Y = function (y) { return oy - y * K; };
        var fonts = { regular: findFont(FONTS.regular), bold: findFont(FONTS.bold) };
        var ink = {
            mullion: swatch(doc, 'Template - Mullion', 0, 0, 0, 80),
            trim: swatch(doc, 'Template - Trim', 0, 100, 0, 0),
            safe: swatch(doc, 'Template - Safe Area', 100, 0, 0, 0),
            label: swatch(doc, 'Template - Text', 0, 0, 0, 100),
            bleed: swatch(doc, 'Template - Bleed', 0, 100, 100, 0),
            check: swatch(doc, 'Template - Check', 0, 100, 100, 0)
        };
        var flagged = {};
        for (i = 0; i < checks.length; i++) {
            flagged[checks[i].id] = true;
        }

        // Layers - each new layer is added on top of the previous one
        var art = doc.layers[0];
        art.name = 'ARTWORK';
        var lMullions = addLayer(doc, 'MULLIONS');
        var lTrim = addLayer(doc, 'TRIM');
        var lSafe = addLayer(doc, 'SAFE AREA');
        var lLabels = addLayer(doc, 'LABELS');
        var lInfo = addLayer(doc, 'INFO');

        // Mullions
        var gh = group(lMullions, 'Horizontal mullions');
        for (i = 0; i < L.horizontal.length; i++) {
            var hm = L.horizontal[i];
            box(gh, X(hm.x), Y(hm.y), hm.w * K, hm.h * K, { fill: ink.mullion }, 'Horizontal mullion ' + (i + 1));
        }
        var gv = null;
        for (i = 0; i < L.vertical.length; i++) {
            var vm = L.vertical[i];
            var rowLetter = LETTERS.charAt(vm.row);
            if (vm.col === 1) {
                gv = group(lMullions, 'Row ' + rowLetter + ' vertical mullions');
            }
            box(gv, X(vm.x), Y(vm.y), vm.w * K, vm.h * K, { fill: ink.mullion },
                'Mullion ' + rowLetter + pad2(vm.col) + '/' + rowLetter + pad2(vm.col + 1));
        }

        // Trim lines, safe areas and labels, grouped by row
        var gTrim = null;
        var gSafe = null;
        var gLabels = null;
        var m = s.safeMargin;
        for (i = 0; i < L.panels.length; i++) {
            p = L.panels[i];
            if (p.col === 1) {
                var rowName = 'Row ' + LETTERS.charAt(p.row);
                gTrim = group(lTrim, rowName + ' trim');
                gSafe = group(lSafe, rowName + ' safe area');
                gLabels = group(lLabels, rowName + ' labels');
            }
            box(gTrim, X(p.x), Y(p.y), p.w * K, p.h * K, { stroke: ink.trim, width: 0.5 }, p.id);
            if (m > 0 && p.w > 2 * m && p.h > 2 * m) {
                box(gSafe, X(p.x + m), Y(p.y + m), (p.w - 2 * m) * K, (p.h - 2 * m) * K,
                    { stroke: ink.safe, width: 0.5, dashes: [4, 2] }, p.id + ' safe area');
            }
            var big = clamp(Math.min(p.h * K * 0.48, p.w * K * 0.2), 6, 96);
            var small = big * 0.6;
            var lines = [p.id, num(p.w) + ' \u00D7 ' + num(p.h)];
            var lineSizes = [big, small];
            var lineFonts = [fonts.bold, fonts.regular];
            var mark = flagged[p.id] && p.h * K >= 150;   // room for a third line
            if (mark) {
                lines.push('CHECK SIZE');
                lineSizes.push(small);
                lineFonts.push(fonts.bold);
            }
            var below = 1.2 * small * (lines.length - 1);
            var baseline = Y(p.y + p.h / 2) - (CAP * big - below) / 2;
            var label = text(gLabels, X(p.x + p.w / 2), baseline, lines, lineSizes, lineFonts,
                ink.label, Justification.CENTER, p.id + ' label');
            if (mark) {
                label.paragraphs[2].characterAttributes.fillColor = ink.check;
            }
        }

        // Row letters left and right, column numbers above and below
        var gKeys = group(lInfo, 'Row and column keys');
        for (r = 0; r < L.rows.length; r++) {
            var rb = L.rows[r];
            var ks = Math.min(72, rb.h * K * 0.8);
            var ky = Y(rb.y + rb.h / 2) - CAP * ks / 2;
            text(gKeys, X(0) - 24, ky, [rb.letter], [ks], [fonts.bold], ink.label, Justification.RIGHT, 'Row ' + rb.letter + ' key (left)');
            text(gKeys, X(L.width) + 24, ky, [rb.letter], [ks], [fonts.bold], ink.label, Justification.LEFT, 'Row ' + rb.letter + ' key (right)');
        }
        var colSize = 48;
        for (i = 0; i < L.panels.length; i++) {
            p = L.panels[i];
            if (p.row === L.topRow) {
                text(gKeys, X(p.x + p.w / 2), Y(0) + 16, [String(p.col)], [colSize], [fonts.bold],
                    ink.label, Justification.CENTER, 'Column ' + p.col + ' key (top)');
            }
            if (p.row === L.bottomRow) {
                text(gKeys, X(p.x + p.w / 2), Y(L.height) - 16 - CAP * colSize, [String(p.col)], [colSize], [fonts.bold],
                    ink.label, Justification.CENTER, 'Column ' + p.col + ' key (bottom)');
            }
        }

        // Title block below the wall
        var gTitle = group(lInfo, 'Title block');
        var tx = X(0);
        var ty = Y(L.height) - 16 - colSize - 150;
        var cols = ROWS[0][1].length;
        var first = LETTERS.charAt(0);
        var last = LETTERS.charAt(L.rows.length - 1);
        var outputRange = '2-' + (L.panels.length + 1);
        var bodySize = 54;
        var butted = buttedRows(WALL);
        var body = [
            'SCALE 1:' + s.scale + ' - everything in this file is ' + num(100 / s.scale) + '% of actual size; output / RIP at ' +
                num(100 * s.scale) + '%. Sizes here and on the panels are actual inches, W \u00D7 H.',
            'Wall ' + num(L.width) + '" W \u00D7 ' + num(L.height) + '" H (' + feetInches(L.width) + ' \u00D7 ' + feetInches(L.height) +
                ')  |  ' + L.panels.length + ' glass panels: rows ' + first + '-' + last +
                (s.firstRowIsTop ? ' (top to bottom)' : ' (bottom to top)') + ' \u00D7 columns 1-' + cols +
                ' (left to right)  |  glass area ' + thousands(L.area) + ' sq ft',
            'Mullions: ' + num(s.verticalMullion) + '" vertical, ' + num(s.horizontalMullion) +
                '" horizontal. Panel sizes are the glass sizes from ' + SOURCE + ' - field-verify before production.',
            butted.length ?
                'No horizontal mullion between rows ' + butted.join(', ') +
                ': those panels butt together on the glass, so their seams will show.' :
                'Every row of glass has a horizontal mullion between it and the next.',
            'Put all artwork on the ARTWORK layer and run it continuously behind the mullions and past the outer edges to the bleed. ' +
                'The other layers are locked, non-printing guides.',
            'Bleed: ' + num(s.bleed) + '" per side (document bleed).  Safe area: keep text and logos ' + num(s.safeMargin) +
                '" inside the panel edges (dashed cyan line).',
            s.panelArtboards ?
                'Output: artboard 1 = whole wall; artboards ' + outputRange + ' = one per panel, named by panel ID. ' +
                'File > Save a Copy > Adobe PDF, Range ' + outputRange + ', Marks and Bleeds > Use Document Bleed Settings.' :
                'Output: artboard 1 = whole wall. Crop each panel to its trim line plus the bleed for output.',
            'Images: ' + num(100 * s.scale) + '-' + num(150 * s.scale) + ' ppi at this scale (100-150 ppi at full size). ' +
                'Set Effect > Document Raster Effects Settings to ' + num(100 * s.scale) + ' ppi or more before output.',
            L.alignment === 'mullions' ?
                'Row widths vary from ' + num(L.minRowWidth) + '" to ' + num(L.maxRowWidth) +
                '", so each row is shifted sideways to line its vertical mullions up with the other rows as closely as the measurements allow.' :
                'Rows are aligned ' + (L.alignment === 'center' ? 'on their centers.' : 'on their ' + L.alignment + ' edges.')
        ];
        if (checks.length) {
            var texts = [];
            for (i = 0; i < checks.length; i++) {
                texts.push(checks[i].id + ': ' + checks[i].text);
            }
            body.push('CHECK BEFORE PRODUCTION: ' + texts.join('; ') + '.');
        }
        var sizes = [];
        var faces = [];
        for (i = 0; i < body.length; i++) {
            sizes.push(bodySize);
            faces.push(fonts.regular);
        }
        text(gTitle, tx, ty - CAP * 120, [PROJECT.toUpperCase() + ' - WINDOW GRAPHICS TEMPLATE ' + REVISION.toUpperCase()], [120], [fonts.bold],
            ink.label, Justification.LEFT, 'Title');
        var bodyTop = ty - 120 - 60;
        text(gTitle, tx, bodyTop - CAP * bodySize, body, sizes, faces, ink.label, Justification.LEFT, 'Notes');
        var bodyBottom = bodyTop - CAP * bodySize - (body.length - 1) * 1.2 * bodySize;

        // Legend
        var chipW = 108;
        var chipH = 54;
        var legendTop = bodyBottom - 110;
        var legend = [
            [{ fill: ink.mullion }, 'Mullion'],
            [{ stroke: ink.trim, width: 3 }, 'Trim line = glass edge (panel size)'],
            [{ stroke: ink.safe, width: 3, dashes: [12, 8] }, 'Safe area'],
            [{ stroke: ink.bleed, width: 3 }, 'Bleed (Illustrator draws it around each artboard)']
        ];
        for (i = 0; i < legend.length; i++) {
            var lx = tx + i * 2600;
            box(gTitle, lx, legendTop, chipW, chipH, legend[i][0], 'Legend ' + (i + 1));
            text(gTitle, lx + chipW + 30, legendTop - chipH / 2 - CAP * bodySize / 2, [legend[i][1]], [bodySize], [fonts.regular],
                ink.label, Justification.LEFT, 'Legend ' + (i + 1) + ' text');
        }

        // Scale bar: 20 ft in 5 ft steps
        var step = 60 * K;
        var barTop = legendTop - chipH - 190;
        text(gTitle, tx, barTop + 30, ['SCALE 1:' + s.scale + ' (5 ft divisions)'], [bodySize], [fonts.bold],
            ink.label, Justification.LEFT, 'Scale bar title');
        for (i = 0; i < 4; i++) {
            box(gTitle, tx + i * step, barTop, step, 36,
                i % 2 ? { stroke: ink.label, width: 2 } : { fill: ink.label, stroke: ink.label, width: 2 }, 'Scale bar ' + (i + 1));
        }
        for (i = 0; i <= 4; i++) {
            text(gTitle, tx + i * step, barTop - 36 - 20 - CAP * 40, [i ? (i * 5) + "'" : '0'], [40], [fonts.regular],
                ink.label, Justification.CENTER, 'Scale bar ' + (i * 5) + ' ft');
        }

        // Artboards: the wall, then one per panel
        doc.artboards[0].name = 'Elevation';
        var made = 1;
        if (s.panelArtboards) {
            if (parseInt(app.version, 10) < 22) {
                notes.push('One artboard per panel needs Illustrator CC 2018 or later - skipped.');
            } else if (L.panels.length + 1 > MAX_ARTBOARDS) {
                notes.push('Too many panels for one artboard each (Illustrator allows ' + MAX_ARTBOARDS + ') - skipped.');
            } else {
                for (i = 0; i < L.panels.length; i++) {
                    p = L.panels[i];
                    doc.artboards.add([X(p.x), Y(p.y), X(p.x + p.w), Y(p.y + p.h)]).name = p.id;
                    made++;
                }
            }
        }
        doc.artboards.setActiveArtboardIndex(0);

        // Lock the template layers and leave ARTWORK ready to use
        var template = [lMullions, lTrim, lSafe, lLabels, lInfo];
        for (i = 0; i < template.length; i++) {
            template[i].printable = false;
            template[i].locked = true;
        }
        doc.activeLayer = art;
        try {
            app.executeMenuCommand('fitall');
        } catch (e) {
            // zoom is only a convenience
        }
        return made;
    }

    function build() {
        var s = SETTINGS;
        var K = 72 / s.scale;   // points per actual inch
        var L = computeLayout(WALL, s);
        var w = L.width * K;
        var h = L.height * K;
        if (w + 2 * 110 > CANVAS || h + 2 * 1800 > CANVAS) {
            alert('At 1:' + s.scale + ' the wall (' + num(L.width) + ' \u00D7 ' + num(L.height) + ' in) does not fit on ' +
                'Illustrator\'s 227 in canvas with its labels. Increase SETTINGS.scale (for example 12 or 20) and run again.');
            return;
        }
        var checks = findChecks(ROWS, NOTES);
        var notes = [];
        var doc = newDocument(w, h, s.bleed * K, notes);
        var savedSystem = app.coordinateSystem;
        var savedLevel = app.userInteractionLevel;
        var artboards;
        app.coordinateSystem = CoordinateSystem.DOCUMENTCOORDINATESYSTEM;
        app.userInteractionLevel = UserInteractionLevel.DONTDISPLAYALERTS;
        try {
            artboards = draw(doc, L, K, checks, notes);
        } finally {
            app.coordinateSystem = savedSystem;
            app.userInteractionLevel = savedLevel;
        }
        for (var i = 0; i < checks.length; i++) {
            notes.push('Check ' + checks[i].id + ': ' + checks[i].text + '.');
        }
        alert('Window graphics template ready.\n\n' +
            L.panels.length + ' panels in ' + L.rows.length + ' rows, ' + artboards + ' artboards.\n' +
            'Scale 1:' + s.scale + ' - output at ' + num(100 * s.scale) + '%.\n' +
            'Wall: ' + num(L.width) + ' \u00D7 ' + num(L.height) + ' in actual.\n\n' +
            'Design on the ARTWORK layer, then File > Save As > Adobe Illustrator (.ai).' +
            (notes.length ? '\n\nNotes:\n- ' + notes.join('\n- ') : ''));
    }

    // Exposed for the build/check tools in tools/ (harmless inside Illustrator)
    global.WINDOW_TEMPLATE = {
        SETTINGS: SETTINGS,
        PROJECT: PROJECT,
        REVISION: REVISION,
        SOURCE: SOURCE,
        MULLION: MULLION,
        WALL: WALL,
        NOTES: NOTES,
        ROWS: ROWS,
        computeLayout: computeLayout,
        findChecks: findChecks,
        buttedRows: buttedRows
    };

    if (typeof app !== 'undefined') {
        if (/illustrator/i.test(app.name)) {
            build();
        } else {
            alert('Please run this script in Adobe Illustrator (File > Scripts > Other Script...).');
        }
    }
}(this));
