// Shared helpers for build.mjs and check.mjs: reading the spreadsheet, writing
// the DATA block of the Illustrator script, and running that script in a
// sandbox that looks like ExtendScript (ES3: no forEach/indexOf/JSON/...).
import vm from 'node:vm';
import { createIllustrator } from './illustrator-mock.mjs';

// ---- spreadsheet ---------------------------------------------------------

export function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  text = text.replace(/^\uFEFF/, '');
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') {
        field += '"';
        i++;
      } else if (ch === '"') {
        quoted = false;
      } else {
        field += ch;
      }
    } else if (ch === '"') {
      quoted = true;
    } else if (ch === ',') {
      row.push(field);
      field = '';
    } else if (ch === '\r' || ch === '\n') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else {
      field += ch;
    }
  }
  if (field !== '' || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

const PANEL = /^(\d+(?:\.\d+)?)"?\s*(?:[xX\u00D7]\s*)?(\d+(?:\.\d+)?)"?$/;
const MULLION = /^(\d+(?:\.\d+)?)"?$/;

// The spreadsheet is drawn like the wall: a header row of column numbers, then
// rows of "W x H" panels (with the 0.5" vertical mullions in between) that
// alternate with rows of 2.25" horizontal mullions.
export function readMeasurements(csvText) {
  const table = parseCsv(csvText)
    .map((r) => r.map((c) => c.trim()))
    .filter((r) => r.some((c) => c !== ''));
  const header = table[0];
  if (!header.filter((c, j) => j % 2 === 0).every((c, k) => c === String(k + 1))) {
    throw new Error('Expected the first row to number the columns 1, 2, 3 ... in every other cell.');
  }
  const rows = [];
  const notes = [];
  const verticalMullions = new Set();
  const horizontalMullions = new Set();
  let lastWasMullion = false;
  table.slice(1).forEach((cells, i) => {
    const line = i + 2;
    const filled = cells.filter((c) => c !== '');
    if (filled.every((c) => MULLION.test(c))) {
      filled.forEach((c) => horizontalMullions.add(parseFloat(c)));
      lastWasMullion = true;
      return;
    }
    lastWasMullion = false;
    const widths = [];
    const heights = new Set();
    const missingX = [];
    cells.forEach((c, j) => {
      if (j % 2 === 1) {
        if (c !== '') {
          if (!MULLION.test(c)) throw new Error(`Line ${line}: expected a mullion size between panels, got "${c}".`);
          verticalMullions.add(parseFloat(c));
        }
        return;
      }
      if (c === '') return;
      const m = c.match(PANEL);
      if (!m) throw new Error(`Line ${line}, column ${j / 2 + 1}: can't read "${c}" as W x H.`);
      if (!/[xX\u00D7]/.test(c)) missingX.push(c);
      widths.push(Number(m[1]));
      heights.add(Number(m[2]));
    });
    if (missingX.length) notes.push(`Line ${line}: ${missingX.length} sizes have no "x" (e.g. ${missingX[0]}) - read as W x H.`);
    if (heights.size !== 1) throw new Error(`Line ${line}: panels in one row must share a height, got ${[...heights].join(', ')}.`);
    rows.push([[...heights][0], widths]);
  });
  return { rows, sill: lastWasMullion, verticalMullions: [...verticalMullions], horizontalMullions: [...horizontalMullions], notes };
}

// ---- the DATA block inside the .jsx --------------------------------------

const LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

export function dataBlock({ project, source, sill, rows }) {
  const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  const lines = rows.map(([h, ws], i) => `        [${h}, [${ws.join(', ')}]]${i < rows.length - 1 ? ',' : ' '} // ${LETTERS[i]}`);
  return [
    '    // @@DATA-BEGIN (generated by tools/build.mjs)',
    `    var PROJECT = ${q(project)};`,
    `    var SOURCE = ${q(source)};`,
    `    var SILL_MULLION = ${sill}; // the spreadsheet ends with a horizontal mullion below the last row`,
    '    var ROWS = [',
    ...lines,
    '    ];',
    '    // @@DATA-END',
  ].join('\n');
}

export function replaceDataBlock(source, block) {
  const re = / {4}\/\/ @@DATA-BEGIN[^\n]*\n[\s\S]*?\/\/ @@DATA-END/;
  if (!re.test(source)) throw new Error('DATA markers not found in the .jsx');
  return source.replace(re, block);
}

// ---- running the script --------------------------------------------------

// Remove what ExtendScript (ES3) doesn't have, so the script can't lean on it.
const EXTENDSCRIPT_BUILTINS = `
(function (g) {
  function drop(o, names) { for (var i = 0; i < names.length; i++) { try { delete o[names[i]]; } catch (e) {} } }
  drop(Array.prototype, ['forEach', 'map', 'filter', 'reduce', 'reduceRight', 'some', 'every', 'indexOf', 'lastIndexOf',
    'find', 'findIndex', 'findLast', 'findLastIndex', 'includes', 'fill', 'flat', 'flatMap', 'keys', 'values', 'entries',
    'at', 'copyWithin', 'toSorted', 'toReversed', 'toSpliced', 'with']);
  drop(Array, ['isArray', 'from', 'of']);
  drop(Object, ['keys', 'values', 'entries', 'create', 'assign', 'freeze', 'isFrozen', 'seal', 'getPrototypeOf',
    'defineProperty', 'defineProperties', 'getOwnPropertyNames', 'getOwnPropertyDescriptor', 'fromEntries']);
  drop(String.prototype, ['trim', 'trimStart', 'trimEnd', 'trimLeft', 'trimRight', 'includes', 'startsWith', 'endsWith',
    'repeat', 'padStart', 'padEnd', 'at', 'codePointAt', 'normalize', 'replaceAll', 'matchAll']);
  drop(Function.prototype, ['bind']);
  drop(Date, ['now']);
  drop(Date.prototype, ['toISOString', 'toJSON']);
  drop(Number, ['isFinite', 'isNaN', 'isInteger', 'parseFloat', 'parseInt', 'EPSILON']);
  drop(Math, ['trunc', 'sign', 'log10', 'log2', 'hypot', 'cbrt', 'fround', 'clz32', 'imul']);
  drop(g, ['JSON', 'Map', 'Set', 'WeakMap', 'WeakSet', 'Promise', 'Symbol', 'Proxy', 'Reflect']);
})(this);
`;

// Runs the .jsx source. With illustratorOptions it runs against the mock
// Illustrator (and builds the document); without, it only defines the script's
// functions. Returns { api, state }.
export function runTemplate(source, { illustratorOptions, es3 = true } = {}) {
  const context = vm.createContext({});
  if (es3) vm.runInContext(EXTENDSCRIPT_BUILTINS, context);
  let state = null;
  if (illustratorOptions) {
    const mock = createIllustrator(illustratorOptions);
    Object.assign(context, mock.globals);
    state = mock.state;
  }
  vm.runInContext(source, context, { filename: 'Figueroa-Windows-Template.jsx' });
  return { api: context.WINDOW_TEMPLATE, state };
}

// Plain copies of values from the sandbox realm.
export const plain = (v) => JSON.parse(JSON.stringify(v));
